### ISSUE TITLE
生成的图片背景色有两种

### ISSUE THREAD

**Issue by jackie19870917** [CB-ysx/pageDesign#11]
为设置图片背景色，保存的图片出现两种背景颜色。

**Comment by jackie19870917** [comment]
[http://yhtpw.com/pageDesign/](url)

**Comment by jackie19870917** [comment]
[我部署地址](http://yhtpw.com/pageDesign/)

**Comment by charlieysx** [comment]
@jackie19870917 你有改过什么吗？我看我的不会呀

**Comment by jackie19870917** [comment]
拉的master分支的代码，然后又Iceworks下载的依赖，改了个title，改了相对路径（config/index.js assetsPublicPath="/" 改为 assetsPublicPath=“./”）,其他代码就没动了。

**Comment by jackie19870917** [comment]
问题解决了， 用yarn下载依赖可以

**Comment by charlieysx** [comment]
@jackie19870917 好的，可能是下载的依赖不一样

**Comment by jackie19870917** [comment]
tks much
