### ISSUE TITLE
本地和打包到服务器显示不一致

### ISSUE THREAD

**Issue by ancin** [CB-ysx/pageDesign#15]
![image](https://user-images.githubusercontent.com/3350461/80332384-49e11a00-887d-11ea-9283-de2690a8fc82.png)

![image](https://user-images.githubusercontent.com/3350461/80332400-51a0be80-887d-11ea-8b9f-a0fc7d58f11d.png)

在本地是好的。
大佬给个建议！

**Comment by charlieysx** [comment]
@ancin 看起来像是element-ui没有加载，你可以看看控制台，是不是element-ui加载失败

**Comment by ancin** [comment]
@CB-ysx  看到问题所在了。大佬V5.
