### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by Fan-zexu** [CB-ysx/pageDesign#2]
我想做一个可以编辑长页面，瀑布流布局的编辑器。
我的元素是使用相对relative定位的，然后操作left , top样式，但是操作起来比absolute复杂很多。
请问大佬有什么更好的解决方案吗？

**Comment by charlieysx** [comment]
这种东西我觉得最好使用absolute @fe-hunk

**Comment by Fan-zexu** [comment]
非常感谢，我打算借鉴你这个项目的经验，把我现有的布局重构一下 😀
我理解用relative渲染，代价有点高，会多次触发回流重绘等问题，而且元素css也非常难处理，也不利于以后扩展
