### ISSUE TITLE
build之后 报错

### ISSUE THREAD

**Issue by LinSundy** [CB-ysx/pageDesign#4]
build之后，在服务器环境下运行， 报element is not defined！

**Comment by charlieysx** [comment]
@LinSundy 是不是element没加载成功，看看network

**Comment by TomeZJ** [comment]
大佬，有加旋转的功能吗？

**Comment by charlieysx** [comment]
@TomeZJ 这个没有加

**Comment by TomeZJ** [comment]
考虑加吗😆


在2019年02月18日 15:57，CodeBear 写道：

@TomeZJ 这个没有加

**Comment by LinSundy** [comment]
externals: {
    'vue': 'Vue',
    'vue-router': 'VueRouter',
    'moment': 'moment',
    'element-ui': 'ELEMENT',
  },

大佬~  element-ui  这改为ELEMENT ~~ 那么多人，就没人发现这个问题吗？

**Comment by LinSundy** [comment]
> 大佬，有加旋转的功能吗？

准备要做~

**Comment by LinSundy** [comment]
> @LinSundy 是不是element没加载成功，看看network
大佬， externals: {
'vue': 'Vue',
'vue-router': 'VueRouter',
'moment': 'moment',
'element-ui': 'ELEMENT',
},
这个webpack.prod.js 中 element-ui 改为 ELEMENT 就好了， 之前从cdn引入element的时候， 找不到变量

**Comment by charlieysx** [comment]
@LinSundy 哈，我线上那demo就是直接这份源码编译的，没出现这个问题，有点奇怪

**Comment by charlieysx** [comment]
@LinSundy 旋转功能加了可以提个pr过来我看看合进去

**Comment by TomeZJ** [comment]
可能是node版本不一样，我之前碰到过类似的问题


在2019年02月18日 17:00，CodeBear 写道：

@LinSundy 哈，我线上那demo就是直接这份源码编译的，没出现这个问题，有点奇怪

**Comment by LinSundy** [comment]
> 可能是node版本不一样，我之前碰到过类似的问题 在2019年02月18日 17:00，CodeBear 写道： @LinSundy 哈，我线上那demo就是直接这份源码编译的，没出现这个问题，有点奇怪 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

因为我在router beforeach中 用到了element的中的组件， 所以才会报这个问题

**Comment by LinSundy** [comment]
大佬这星我那天看不是5000+以上吗 ？ 怎么变成154了。。

**Comment by charlieysx** [comment]
@LinSundy 你看错了吧

**Comment by LinSundy** [comment]
> @LinSundy 你看错了吧

这代码 没有5000+的星， 天理难容啊~  你可帮我大忙了。。😆
